language: julia

os:
  - linux
  - osx

julia:
#  - 1.0
  - 1.5
#  - nightly

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
matrix:
   allow_failures:
    - os: osx
#   - julia: 1.5
#   - julia: nightly

notifications:
  email: false

install:
  - utils/ci-test-install

script: # the default script is equivalent to the following
  - utils/ci-test-run
