environment:
  matrix:
#  - julia_version: 1.0
  - julia_version: 1.3

platform:
#  - x86 # 32-bit
  - x64 # 64-bit

branches:
  only:
    - master
    - Alex
    - /Alex-.*/
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - ps: python -Wignore -m pip --user matplotlib
  - ps: python -Wignore -m pip --user jupyter
  - C:\julia\bin\julia --project --eval 'using Pkg; Pkg.instantiate();'
  - C:\julia\bin\julia --project --eval 'using Pkg; Pkg.status();'
  - C:\julia\bin\julia --project --eval 'using Pkg; Pkg.add(PackageSpec(name="DIVAnd", rev="master"));'
  - ps: python -m jupyter kernelspec list

test_script:
  - bash utils/test-notebooks