environment:
  matrix:
  - julia_version: 1

platform:
#  - x86 # 32-bit
  - x64 # 64-bit

branches:
  only:
    - master
    - Alex
    - /Alex-.*/
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - ps: $env:Path = "C:\Python38-x64;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts;C:\julia\bin\;$env:Path"
  - python -Wignore -m pip install --user matplotlib
  - python -Wignore -m pip install --user jupyter
  - C:\julia\bin\julia --project --eval "using Pkg; Pkg.instantiate();"
  - C:\julia\bin\julia --project --eval "using Pkg; Pkg.status();"
  - C:\julia\bin\julia --project --eval "using Pkg; Pkg.add(PackageSpec(name="""DIVAnd""", rev="""master"""));"
  - jupyter kernelspec list

test_script:
  - ps: $env:Path = "C:\Python38-x64;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts;C:\julia\bin\;$env:Path"
  - bash utils/ci-test
